[General]
# List of plugins that should not be loaded on bluetoothd startup
#DisablePlugins = network,input
# Default adaper name
# %h - substituted for hostname
# %d - substituted for adapter id
Name = Playstation Classic (AutoBleem)
# Default device class. Only the major and minor device class bits are
# considered.
Class = 0x000100

DiscoverableTimeout = 0
Discoverable=true

# How long to stay in pairable mode before going back to non-discoverable
# The value is in seconds. Default is 0.
# 0 = disable timer, i.e. stay pairable forever
PairableTimeout = 0

[Policy]
AutoEnable=true

