787 stream tcp nowait root bluetoothctl bluetoothctl
#21 stream tcp nowait root ftpd ftpd /
#22 stream tcp nowait root dropbear dropbear -r /etc/dropbear_key -i
23 stream tcp nowait root telnetd telnetd -i

